### ISSUE TITLE
ROCKER not available

### ISSUE THREAD

**Issue by CLG68** [jvlehtonen/brutenib#2]
Hi,

ROCKER is not available anymore on https://medchem.fi/rocker/.   It is just to let you know as I already have a copy that I corrected and slightly modified to be compatible with Python 3.X, so it not a problem for me.

Best,
Christian

**Comment by jvlehtonen** [comment]
I've passed a note to maintainers of ROCKER, although that is something you too could have done. They could be interested in your changes.

**Comment by CLG68** [comment]
Thank you,
I already sent an email to inform them of that problem with their download page.  They did not answer back or correct the problem.  So, it was just to let you know as your tool relies on ROCKER.

Best,
Christian
